server:
  address: ":8000"
  clientMaxBodySize: "2MB"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  path: "./log"   # 日志文件路径。默认为空，表示关闭，仅输出到终端
  file: "{Y-m-d}.log"
  level: "all"
  stdout: true

upload:
  prefix: "http://127.0.0.1:8001/static" # url文件访问前缀，通常交给web服务器来解析静态资源
  path: "D:/project/oldme-api/static" # 使用绝对路径

database:
  logger:
    path: "./log/sql"
    level: "all"
    stdout: true
  default:
    link:   "mysql:root:JCPHqknyy8ATR5ME@tcp(192.168.10.47:3306)/oldme?loc=Local"
    debug:  false
