
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  gen:
    dao:
      - link:            "mysql:root:JCPHqknyy8ATR5ME@tcp(192.168.10.47:3306)/oldme"
        descriptionTag:  true
        noModelComment:  true

  build:
    name: "oldme"
    arch: "amd64"
    system: "windows"
    mod: "none"
    packSrc: "resource,manifest"
    extra: ""