// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/oldme-git/oldme-api/internal/dao/internal"
)

// sayingDao is the data access object for the table saying.
// You can define custom methods on it to extend its functionality as needed.
type sayingDao struct {
	*internal.SayingDao
}

var (
	// Saying is a globally accessible object for table saying operations.
	Saying = sayingDao{internal.NewSayingDao()}
)

// Add your custom methods and functionality below.
