// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/oldme-git/oldme-api/internal/dao/internal"
)

// wordDao is the data access object for the table word.
// You can define custom methods on it to extend its functionality as needed.
type wordDao struct {
	*internal.WordDao
}

var (
	// Word is a globally accessible object for table word operations.
	Word = wordDao{internal.NewWordDao()}
)

// Add your custom methods and functionality below.
